"""Tests for bank parser helpers."""

from __future__ import annotations

from io import BytesIO, StringIO

import pandas as pd

from src.ingestion.bank_csv_parser import parse_bank_csv, parse_bank_excel
from src.utils.validation import validate_required_columns


def test_parse_bank_csv_maps_common_columns():
    csv_content = StringIO(
        "Transaction Date,Description,Withdrawal,Deposit,Closing Balance\n"
        "2026-05-01,Opening balance,0,1000,1000\n"
    )

    df = parse_bank_csv(csv_content)

    assert {"date", "narration", "debit", "credit", "balance_amount", "balance"}.issubset(df.columns)


def test_validate_required_bank_columns_returns_valid():
    csv_content = StringIO(
        "Transaction Date,Description,Withdrawal,Deposit,Closing Balance\n"
        "2026-05-01,Opening balance,0,1000,1000\n"
    )

    df = parse_bank_csv(csv_content)
    result = validate_required_columns(df, ["date", "narration", "debit", "credit", "balance_amount"])

    assert result["is_valid"] is True


def test_parse_bank_csv_coalesces_duplicate_date_columns():
    csv_content = StringIO(
        "Transaction Date,Value Date,Description,Withdrawal,Deposit,Closing Balance,Reference Number\n"
        "2026-05-01,2026-05-02,Opening balance,0,1000,1000,REF-001\n"
    )

    df = parse_bank_csv(csv_content)

    assert list(df.columns).count("date") == 1
    assert df.loc[0, "date"] == "2026-05-01"


def test_parse_bank_csv_splits_signed_amount_column():
    csv_content = StringIO(
        "Txn Date,Transaction Details,Transaction Amount,Running Balance\n"
        "2026-05-01,Client receipt,12500,12500\n"
        "2026-05-02,Vendor payment,-4500,8000\n"
    )

    df = parse_bank_csv(csv_content)

    assert df.loc[0, "credit"] == 12500
    assert df.loc[0, "debit"] == 0
    assert df.loc[1, "debit"] == 4500
    assert df.loc[1, "credit"] == 0
    assert df.loc[1, "balance_amount"] == 8000


def test_parse_bank_excel_handles_title_rows_and_real_bank_labels():
    workbook_rows = [
        ["Statement for Account 1234", None, None, None, None],
        ["Generated by Bank", None, None, None, None],
        ["Value Date", "Particulars", "Paid Out", "Paid In", "Closing Balance"],
        ["01/05/2026", "Opening balance", "", "₹1,000.00", "₹1,000.00"],
        ["02/05/2026", "Office rent", "₹250.00", "", "₹750.00"],
    ]

    buffer = BytesIO()
    pd.DataFrame(workbook_rows).to_excel(buffer, index=False, header=False)
    buffer.seek(0)

    df = parse_bank_excel(buffer)

    assert {"date", "narration", "debit", "credit", "balance_amount"}.issubset(df.columns)
    assert df.loc[0, "narration"] == "Opening balance"
    assert df.loc[0, "credit"] == 1000.0
    assert df.loc[1, "debit"] == 250.0
